name: ghpages

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.2.4
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        # hugo-version: # optional, default is latest
        # Download (if necessary) and use Hugo extended version. Example: true
        extended: true # optional, default is false

    - name: Build
      run: hugo --minify
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
